### ISSUE TITLE
<EMPH> in generated HTML

### ISSUE THREAD

**Issue by KZiemian** [Clozure/ccldoc#16]
In my code of CCLDoc I used string embedded syntax
``{:emphasis new-symbol}``
which in HTML file expand (right word?) to
``<EMPH>new-symbol</EMPH>``
and on web page "new symbol" is not write in cursive. I not very good in HTML, but after some searching I find that that tag for emphasis is ``<em>``. Is something wrong or is the deeper meaning to it, which I don't get?

**Comment by xrme** [comment]
That is a bug in the html renderer.

Instead of the `<emph>` tag (which, as you point out, does not exist), the html renderer should emit the `<em>` tag.

This would be a great first issue if you want to submit a pull request correcting this bug.  The problem code appears to be https://github.com/Clozure/ccldoc/blob/master/source/output-html.lisp#L195

**Comment by xrme** [comment]
closed by #17
